[package]
name = "movies-website"
version = "0.1.0"
authors = []
edition = "2021"
publish = false

[workspace]
members = [".", "api", "core", "entity", "migration"]

[dependencies]
api = { path = "api" }
