[package]
name = "movies-website"
version = "0.1.0"
authors = []
edition = "2021"
publish = false
default-run = "movies-website"

[workspace]
members = [".", "api", "core", "entity", "migration", "macros"]

[dependencies]
api = { path = "api" }
clap = { version = "4.3.0", features = ["derive"] }
serde = "1.0.163"
serde_json = "1.0.96"
