[package]
name = "movies-migration"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
regex = { version = "1", features = ["unicode-case"] }
sea-orm-migration.workspace = true
