[package]
name = "movies-entity"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
sea-orm.workspace = true
serde.workspace = true
utoipa.workspace = true
